### PR TITLE
Changed hover color of links

### PR DESCRIPTION
**Pull request by V3dant**
#91

### CODE REVIEW

**Comment by V3dant** [comment]
Changed hover color of links

**Comment by smkamranqadri** [comment]
class name a does not mean anything, it should be a proper name, maybe color-midnight-hover and make sure locally it's working, icons may need fill property, not colors.

**Comment by V3dant** [comment]
It doesn't seem to work locally I don't know why and there's no guide to run it in the README.md file. Can you help me out with that?

**Comment by smkamranqadri** [comment]
Oh! my bad, you need to install ruby, gem and Jekyll to run.

**Pull request closed without merging**
