### PR TITLE
solved issue #71

### PR DESCRIPTION
**Pull request by Sayan-dev**
Solved conflicts regarding avatar and avtar,  if no image visible a single image is visible

### CODE REVIEW

**Comment by smkamranqadri** [comment]
I merged it but it's better not to work on the master branch when contributing.

**Comment by smkamranqadri** [comment]
What does it do, we don't have dev.avtar key?

{% elsif dev.avtar %}{{ dev.avtar }}

**Comment by smkamranqadri** [comment]
these are the mistake people did, we can fix it.

avtar

**Comment by Sayan-dev** [comment]
ya we can definitely solve that..but i thought this would be a more
generalized solution than changing all avtar to avatar

**Comment by smkamranqadri** [comment]
I understand but handle problem is not the solution, we need to resolve the problem.

**Comment by Sayan-dev** [comment]
Hey,

I just signed the petition "Indian Judiciary: Hang the criminal(s) of Priya
Reddy Rape/Murder case before the 2019 year end" and wanted to see if you
could help by adding your name.

Our goal is to reach 7,500 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/fZdr9CGJct

Thanks!
Sayanta

**Comment by Sayan-dev** [comment]
Hey,

I just signed the petition "Maulana Abul Kalam Azad University of
Technology: Amendment of the 4th SEM Routine of Computer Science
Engineering under MAKAUT" and wanted to see if you could help by adding
your name.

Our goal is to reach 100 signatures and we need more support. You can read
more and sign the petition here:

http://chng.it/hmtqGdktLG

Thanks!
Sayanta

**Comment by Sayan-dev** [comment]
Hey,

I just signed the petition "Sony Music India and Badshah: Pay Ratan Kahar
royalties or take down ‘Genda Phool’" and wanted to see if you could help
by adding your name.

Our goal is to reach 15,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/DNFvqwFqvM

Thanks!
Sayanta

**Pull request merged**
